### ISSUE TITLE
Following "Getting Started" in README.md leads to "No module named 'openai'" error

### ISSUE THREAD

**Issue by DonaldKellett** [pynecone-io/pynecone-chat#16]
Following "Getting Started" in README.md leads to "No module named 'openai'" error:

[![asciicast](https://asciinema.org/a/626053.svg)](https://asciinema.org/a/626053)

Seeing as the `openai` dependency is specified in `webui/requirements.txt` which should solve the issue, consider changing the README instructions as follows:

```bash
git clone https://github.com/reflex-dev/reflex-chat.git
pip install -r reflex-chat/webui/requirements.txt
cd reflex-chat/webui/
reflex init
reflex run
```

**Comment by picklelo** [comment]
Good call, will try to update this. Or if anyone has time to put up a PR for this will be happy to merge!
